# Generated by Django 3.0.7 on 2020-06-29 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Unique_ID', models.CharField(blank=True, max_length=99999)),
                ('Email', models.CharField(blank=True, max_length=99999)),
                ('Contact', models.CharField(blank=True, max_length=99999)),
                ('Verified', models.CharField(blank=True, max_length=99999)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
