# Generated by Django 3.0.7 on 2020-06-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assignment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Verified',
        ),
        migrations.AddField(
            model_name='profile',
            name='Email_Verified',
            field=models.CharField(blank=True, max_length=99999),
        ),
        migrations.AddField(
            model_name='profile',
            name='Phone_Verified',
            field=models.CharField(blank=True, max_length=99999),
        ),
    ]
