# Generated by Django 3.0.7 on 2020-06-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assignment', '0002_auto_20200629_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Email_Verified',
            field=models.CharField(blank=True, default='False', max_length=99999),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Phone_Verified',
            field=models.CharField(blank=True, default='False', max_length=99999),
        ),
    ]
